In [2]:
import numpy as np

In [3]:
l1 = [1,2,3,4]

In [4]:
n1=np.array(l1)

In [5]:
type(n1)

numpy.ndarray

In [6]:
n2=np.array([[1,2,3,4],[5,6,7,8]])

In [7]:
type(n2)

numpy.ndarray

In [8]:
n2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
#initializing Numpy Array with zero

In [9]:
n3=np.zeros((1,2))

In [10]:
n3

array([[0., 0.]])

In [11]:
type(n3)

numpy.ndarray

In [12]:
n4=np.zeros((5,5))#5x5 matrix created

In [13]:
n4

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
#initializing Numpy Array with same number

In [14]:
n5=np.full((2,3),4)

In [15]:
n5

array([[4, 4, 4],
       [4, 4, 4]])

In [16]:
#initializing Numpy Array with a range

In [17]:
n6=np.arange(1,10)
n6

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
n7=np.arange(0,30,5) #here 5 means numver of list is 5
n7

array([ 0,  5, 10, 15, 20, 25])

In [20]:
#initializing Numpy Array with random number

In [21]:
n8=np.random.randint(0,100,10) #here 10 means number of random value is 10
n8

array([69, 20, 98,  5, 84,  6, 33, 42,  6, 83])

In [24]:
#checking the shape of NUmpy Array

In [32]:
n9=np.array([[1,2,3,4],[5,6,7,8]])
n9

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [33]:
n9.shape

(2, 4)

In [34]:
n9.shape =(4,2) #converting numpy array shape from 2x4 to 4x2

In [35]:
n9

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])